#!/bin/sh

s_word="(\*FAST\*)Admitted"
t_word="(\*FAST\*)Qed"

for file in `find . -name "*.v"`
do
  res=`grep "$s_word" $file`
  if [ -n "$res" ]
  then
    echo "substitute $s_word with $t_word in $file ..."
    cp $file ${file}~
    sed "s/$s_word/$t_word/g" < ${file}~ > $file
    rm -f ${file}~
  fi
done
